export type CsLearningLanguage = 'en' | 'ja';

export function normalizeCsLearningLanguage(language: unknown): CsLearningLanguage {
  return typeof language === 'string' && language.toLowerCase().startsWith('ja') ? 'ja' : 'en';
}

export const csLearningCopy = {
  en: {
    common: {
      csLearningLab: 'CS Learning Lab',
      sortingLab: 'Sorting Lab',
      cryptoLab: 'Crypto Lab',
      bigOComparison: 'Big-O Comparison',
      open: 'Open',
      run: 'Run',
      check: 'Check',
      quickQuiz: 'Quick quiz',
      pick: 'Pick',
      complexity: 'Complexity',
      stable: 'Stable',
      notStable: 'Not stable',
      inPlace: 'In-place',
      extraMemory: 'Extra memory',
      best: 'Best',
      average: 'Average',
      worst: 'Worst',
      space: 'Space',
      comparisons: 'Comparisons',
      writesSwaps: 'Writes/Swaps',
      noOutput: 'No output',
    },
    home: {
      kicker: 'Interactive study section',
      title: 'CS Learning Lab',
      subtitle:
        'Algorithms and cryptography as hands-on lessons: run the process, inspect each step, compare complexity, and answer short checks inside the same flow.',
      startSorting: 'Start Sorting Lab',
      openCrypto: 'Open Crypto Lab',
      learningFlowLabel: 'Learning flow',
      flowTitle: 'Lab flow',
      flow: [
        {
          title: 'Predict',
          text: 'Start with a small guess before the animation runs.',
        },
        {
          title: 'Run',
          text: 'Step through comparisons, swaps, keys, and modular arithmetic.',
        },
        {
          title: 'Explain',
          text: 'Connect each operation to the concept it demonstrates.',
        },
        {
          title: 'Quiz',
          text: 'Check the idea immediately while the example is still visible.',
        },
      ],
      tracksEyebrow: 'Tracks',
      tracksTitle: 'Study by running small systems',
      tracksText:
        'The first version focuses on sort visualizers and cryptography playgrounds. The structure leaves room for graphs, data structures, probability, and machine learning later.',
      sortingTitle: 'Sorting Algorithms',
      sortingText:
        'Compare adjacent swaps, selected minimums, inserted keys, merges, partitions, and heap extraction with one shared visualizer.',
      complexityTitle: 'Complexity Lab',
      complexityText:
        'Place O(n), O(n log n), and O(n^2) side by side so growth rate differences are visible before code timing gets noisy.',
      cryptoTitle: 'Cryptography',
      cryptoText:
        'Move from Caesar and Vigenere to XOR, RSA, key exchange, and hashing with parameter controls and step cards.',
      visualizer: 'Visualizer',
      comparison: 'Comparison',
      playground: 'Playground',
      sortsBadge: '{{count}} sorts',
      topicsBadge: '{{count}} topics',
      mapEyebrow: 'Current map',
      mapTitle: 'Algorithms and cryptography are ready to branch out',
      studyArticles: 'Study Articles',
      algorithms: 'Algorithms',
      sortingSet: 'Sorting set',
      cryptography: 'Cryptography',
      techniqueSet: 'Technique set',
      nextEyebrow: 'Next extension',
      nextTitle: 'Progress, generated quizzes, and review can attach here',
      nextText:
        'This version is intentionally browser-first. Firestore progress and Cloud Functions for AI-generated questions can be added without changing the lab routes.',
    },
    sortingOverview: {
      algorithms: 'Algorithms',
      title: 'Sorting Lab',
      subtitle:
        'One visual model for adjacent swaps, selected minimums, insertion shifts, merge writes, pivot partitions, and heap extraction.',
      visualizerSet: 'Visualizer set',
      chooseAlgorithm: 'Choose an algorithm',
      growth: 'Growth',
      growthTitle: 'Quadratic growth becomes visible fast',
      growthText:
        'Browser timing can be noisy, so this lab starts with theoretical operation counts. The shape is the concept.',
      openChart: 'Open Chart',
      chartLabel: 'Complexity sample chart',
      chartLegend: 'Chart legend',
      red: 'Red: O(n^2)',
      blue: 'Blue: O(n log n)',
      green: 'Green: O(n)',
    },
    sortLab: {
      algorithmVisualizer: 'Algorithm visualizer',
      labAria: '{{name}} interactive lab',
      phases: {
        setup: 'setup',
        compare: 'compare',
        swap: 'swap',
        write: 'write',
        partition: 'partition',
        complete: 'complete',
      },
      stepThrough: 'Step through the array',
      step: 'Step {{current}} / {{total}}: {{note}}',
      playbackControls: 'Playback controls',
      firstStep: 'First step',
      previousStep: 'Previous step',
      play: 'Play',
      pause: 'Pause',
      nextStep: 'Next step',
      lastStep: 'Last step',
      reset: 'Reset',
      shuffleInput: 'Shuffle input',
      arrayValues: 'Array values',
      speed: 'Speed',
      algorithms: 'Algorithms',
      arrayVisualization: 'Array visualization',
      barLabel: 'Index {{index}}, value {{value}}',
    },
    bigO: {
      complexity: 'Complexity',
      title: 'Big-O Comparison',
      subtitle:
        'Theoretical growth makes the difference between linear, n log n, and quadratic work easier to see than raw browser timing.',
      chart: 'Chart',
      growthByInput: 'Growth by input size',
      numbers: 'Numbers',
      sampleCounts: 'Sample operation counts',
      sortMap: 'Sort map',
      whereSortLands: 'Where each sort lands',
    },
    cryptoOverview: {
      cryptography: 'Cryptography',
      title: 'Crypto Lab',
      subtitle:
        'Explore classical ciphers, symmetric ideas, public-key arithmetic, key exchange, and hashing with small inspectable examples.',
      startRsa: 'Start with RSA',
      techniqueSet: 'Technique set',
      choosePlayground: 'Choose a playground',
      interactive: 'Interactive',
      securityBoundary: 'Security boundary',
      securityTitle: 'These demos explain ideas, not production security',
      securityText:
        'The lab intentionally uses small values and transparent steps. Real systems should rely on modern, reviewed libraries and protocols.',
    },
    cryptoLab: {
      labAria: '{{name}} playground',
      playground: 'Playground',
      inspect: 'Change inputs and inspect the transformation',
      resetInputs: 'Reset inputs',
      output: 'Output',
      steps: 'Steps',
      trace: 'Transformation trace',
      techniques: 'Techniques',
      boundary: 'Boundary',
      securityNote: 'Security note',
      message: 'Message',
      shift: 'Shift',
      keyword: 'Keyword',
      keywordAlphabetSeed: 'Keyword alphabet seed',
      rails: 'Rails',
      xorKey: 'XOR key',
      messageNumber: 'Message number',
      primeP: 'Prime p',
      generatorG: 'Generator g',
      alicePrivate: 'Alice private',
      bobPrivate: 'Bob private',
    },
  },
  ja: {
    common: {
      csLearningLab: 'CSラーニングラボ',
      sortingLab: 'ソートラボ',
      cryptoLab: '暗号ラボ',
      bigOComparison: 'Big-O比較',
      open: '開く',
      run: '実行',
      check: '確認',
      quickQuiz: 'ミニクイズ',
      pick: '選択',
      complexity: '計算量',
      stable: '安定',
      notStable: '不安定',
      inPlace: 'インプレース',
      extraMemory: '追加メモリ',
      best: '最良',
      average: '平均',
      worst: '最悪',
      space: '空間',
      comparisons: '比較',
      writesSwaps: '書き込み/交換',
      noOutput: '出力なし',
    },
    home: {
      kicker: 'インタラクティブ学習セクション',
      title: 'CSラーニングラボ',
      subtitle:
        'アルゴリズムと暗号を手で動かして学ぶ教材です。処理を実行し、各ステップを観察し、計算量を比べ、短い確認問題まで同じ流れで進めます。',
      startSorting: 'ソートラボを始める',
      openCrypto: '暗号ラボを開く',
      learningFlowLabel: '学習フロー',
      flowTitle: 'ラボの流れ',
      flow: [
        {
          title: '予想',
          text: 'アニメーションを動かす前に、小さな入力で結果を予想します。',
        },
        {
          title: '実行',
          text: '比較、交換、鍵、剰余計算をステップごとに追います。',
        },
        {
          title: '説明',
          text: '各操作がどの概念を表しているかを結びつけます。',
        },
        {
          title: 'クイズ',
          text: '例が見えているうちに、考え方を短い問題で確認します。',
        },
      ],
      tracksEyebrow: 'トラック',
      tracksTitle: '小さな仕組みを動かして学ぶ',
      tracksText:
        '最初の版ではソート可視化と暗号プレイグラウンドに集中しています。今後、グラフ、データ構造、確率、機械学習にも広げられる構成です。',
      sortingTitle: 'ソートアルゴリズム',
      sortingText:
        '隣接交換、最小値選択、挿入、マージ、ピボット分割、ヒープ抽出を同じ可視化モデルで比べます。',
      complexityTitle: '計算量ラボ',
      complexityText:
        'O(n)、O(n log n)、O(n^2) を並べて、実行時間のノイズより前に増え方の違いを見えるようにします。',
      cryptoTitle: '暗号',
      cryptoText:
        'Caesar、VigenereからXOR、RSA、鍵交換、ハッシュまで、パラメータ操作とステップカードで追います。',
      visualizer: '可視化',
      comparison: '比較',
      playground: 'プレイグラウンド',
      sortsBadge: '{{count}}種類のソート',
      topicsBadge: '{{count}}トピック',
      mapEyebrow: '現在のマップ',
      mapTitle: 'アルゴリズムと暗号を起点に拡張できる状態です',
      studyArticles: '学習記事',
      algorithms: 'アルゴリズム',
      sortingSet: 'ソート一覧',
      cryptography: '暗号',
      techniqueSet: '手法一覧',
      nextEyebrow: '次の拡張',
      nextTitle: '進捗、生成クイズ、復習をここへ接続できます',
      nextText:
        'この版はブラウザで完結することを優先しています。Firestoreの進捗やCloud FunctionsによるAI生成問題は、ラボのルートを変えずに追加できます。',
    },
    sortingOverview: {
      algorithms: 'アルゴリズム',
      title: 'ソートラボ',
      subtitle:
        '隣接交換、最小値選択、挿入によるシフト、マージ書き込み、ピボット分割、ヒープ抽出を1つの可視化モデルで見ます。',
      visualizerSet: '可視化セット',
      chooseAlgorithm: 'アルゴリズムを選ぶ',
      growth: '増え方',
      growthTitle: '二乗の増え方はすぐに見えてくる',
      growthText:
        'ブラウザの実測時間はぶれやすいので、このラボでは理論上の操作回数から始めます。大事なのは曲線の形です。',
      openChart: 'グラフを開く',
      chartLabel: '計算量サンプルグラフ',
      chartLegend: 'グラフ凡例',
      red: '赤: O(n^2)',
      blue: '青: O(n log n)',
      green: '緑: O(n)',
    },
    sortLab: {
      algorithmVisualizer: 'アルゴリズム可視化',
      labAria: '{{name}} インタラクティブラボ',
      phases: {
        setup: '準備',
        compare: '比較',
        swap: '交換',
        write: '書き込み',
        partition: '分割',
        complete: '完了',
      },
      stepThrough: '配列をステップ実行する',
      step: 'ステップ {{current}} / {{total}}: {{note}}',
      playbackControls: '再生コントロール',
      firstStep: '最初のステップ',
      previousStep: '前のステップ',
      play: '再生',
      pause: '一時停止',
      nextStep: '次のステップ',
      lastStep: '最後のステップ',
      reset: 'リセット',
      shuffleInput: '入力をシャッフル',
      arrayValues: '配列の値',
      speed: '速度',
      algorithms: 'アルゴリズム',
      arrayVisualization: '配列の可視化',
      barLabel: 'インデックス {{index}}、値 {{value}}',
    },
    bigO: {
      complexity: '計算量',
      title: 'Big-O比較',
      subtitle:
        '線形、n log n、二乗の作業量の違いは、ブラウザの実測時間より理論上の増え方を見るほうが理解しやすくなります。',
      chart: 'グラフ',
      growthByInput: '入力サイズごとの増え方',
      numbers: '数値',
      sampleCounts: 'サンプル操作回数',
      sortMap: 'ソートの位置づけ',
      whereSortLands: '各ソートがどこに位置するか',
    },
    cryptoOverview: {
      cryptography: '暗号',
      title: '暗号ラボ',
      subtitle:
        '古典暗号、共通鍵の考え方、公開鍵の計算、鍵交換、ハッシュを小さく観察できる例で学びます。',
      startRsa: 'RSAから始める',
      techniqueSet: '手法一覧',
      choosePlayground: 'プレイグラウンドを選ぶ',
      interactive: 'インタラクティブ',
      securityBoundary: 'セキュリティ上の境界',
      securityTitle: 'このデモは考え方の説明用で、本番セキュリティではありません',
      securityText:
        'ラボでは小さな値と透明な手順を使っています。実際のシステムでは、レビュー済みの現代的なライブラリとプロトコルを使うべきです。',
    },
    cryptoLab: {
      labAria: '{{name}} プレイグラウンド',
      playground: 'プレイグラウンド',
      inspect: '入力を変えて変換を観察する',
      resetInputs: '入力をリセット',
      output: '出力',
      steps: '手順',
      trace: '変換トレース',
      techniques: '手法',
      boundary: '境界',
      securityNote: 'セキュリティメモ',
      message: 'メッセージ',
      shift: 'シフト',
      keyword: 'キーワード',
      keywordAlphabetSeed: 'キーワードアルファベットの種',
      rails: 'レール数',
      xorKey: 'XORキー',
      messageNumber: 'メッセージ番号',
      primeP: '素数 p',
      generatorG: '生成元 g',
      alicePrivate: 'Aliceの秘密値',
      bobPrivate: 'Bobの秘密値',
    },
  },
} as const;

export function getCsLearningCopy(language: unknown) {
  return csLearningCopy[normalizeCsLearningLanguage(language)];
}

export function formatCsLearningCopy(
  template: string,
  values: Record<string, string | number>
) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(values[key] ?? ''));
}
