/**
 * Shared games data
 */

export interface Game {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  path: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: string;
}

export const games: Game[] = [
  {
    id: 'jump-game',
    title: 'Jump Game',
    description: 'A classic jump-and-dodge arcade game. Press any key to jump over obstacles and rack up points!',
    thumbnail: '🎮',
    path: '/games/jump-game',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Challenge the AI in this classic strategy game! Choose from Easy, Medium, or Hard difficulty and test your skills.',
    thumbnail: '⭕',
    path: '/games/tic-tac-toe',
    difficulty: 'Medium',
    category: 'Strategy',
  },
  {
    id: 'gomoku',
    title: 'Gomoku',
    description: 'Five in a Row! Strategic board game with AI using minimax and alpha-beta pruning. Can you outsmart the algorithm?',
    thumbnail: '⚫',
    path: '/games/gomoku',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    description: 'Classic block-stacking puzzle game. Clear lines by completing horizontal rows. Speed increases as you level up!',
    thumbnail: '🟦',
    path: '/games/tetris',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'shogi',
    title: 'Shogi',
    description: 'Japanese Chess! Strategic board game with piece drops and promotions. Challenge the AI in this classic strategy game!',
    thumbnail: '☗',
    path: '/games/shogi',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'othello',
    title: 'Othello',
    description: 'Classic strategy board game with AI using alpha-beta search. Flip your opponent\'s discs to win!',
    thumbnail: '⚫',
    path: '/games/othello',
    difficulty: 'Medium',
    category: 'Strategy',
  },
  {
    id: 'mini-adventure',
    title: 'Mini Adventure',
    description: 'Roguelike dungeon crawler! Descend 10 floors, manage your torch, and defeat the Dragon boss!',
    thumbnail: '🗡️',
    path: '/games/mini-adventure',
    difficulty: 'Hard',
    category: 'RPG',
  },
  {
    id: 'animal-roleplay',
    title: 'Animal Roleplay',
    description: 'Become an animal and survive 10 turns. Choose actions each turn to manage HP and hunger and reach the best score.',
    thumbnail: '🦊',
    path: '/games/animal-roleplay',
    difficulty: 'Medium',
    category: 'RPG',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Classic brick-breaking arcade game! Use your paddle to bounce the ball and destroy all bricks. Collect power-ups!',
    thumbnail: '🧱',
    path: '/games/breakout',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    description: 'Defend Earth from alien invasion! Destroy waves of enemies, use shields for cover, and shoot the mystery UFO for bonus points.',
    thumbnail: '👾',
    path: '/games/space-invaders',
    difficulty: 'Medium',
    category: 'Arcade',
  },
  {
    id: 'daifugo',
    title: 'Daifugo',
    description: 'Play Daifugo (大富豪) vs AI (3–6 players) or online (3–6 players). Create a room, share the code, and battle to empty your hand first!',
    thumbnail: '🃏',
    path: '/games/daifugo',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'shichinarabe',
    title: 'Shichinarabe',
    description: 'Play Shichinarabe (七並べ) vs AI (3–6 players) or online (3–6 players). Place cards around 7s and race to empty your hand!',
    thumbnail: '🃏',
    path: '/games/shichinarabe',
    difficulty: 'Easy',
    category: 'Card',
  },
  {
    id: 'doubt',
    title: 'Doubt',
    description: 'Play Doubt (ダウト) vs AI (3–6 players) or online (3–6 players). Play face-down cards, claim the rank, and call Doubt to catch bluffs!',
    thumbnail: '🃏',
    path: '/games/doubt',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'reverse-jump',
    title: 'Reverse Jump',
    description: 'Controls flip every 8 seconds. Jump low obstacles, duck high bars, and survive the chaos.',
    thumbnail: '↕️',
    path: '/games/reverse-jump',
    difficulty: 'Medium',
    category: 'Arcade',
  },
  {
    id: 'ghost-tetris',
    title: 'Ghost Tetris',
    description: 'Locked blocks fade after 2 seconds. Rely on memory to keep clearing lines.',
    thumbnail: '👻',
    path: '/games/ghost-tetris',
    difficulty: 'Hard',
    category: 'Puzzle',
  },
  {
    id: 'chaos-breakout',
    title: 'Chaos Breakout',
    description: 'Every 10 seconds, gravity, speed, or paddle width changes. Adapt or lose.',
    thumbnail: '💥',
    path: '/games/chaos-breakout',
    difficulty: 'Hard',
    category: 'Arcade',
  },
  {
    id: 'doubt-word',
    title: 'Doubt Word',
    description: 'A bluff battle with claimed first letters and word lengths. Believe or call Doubt.',
    thumbnail: '🧠',
    path: '/games/doubt-word',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'timed-button',
    title: 'Timed Button',
    description: 'Pass the bomb before it explodes. One button, pure mind game.',
    thumbnail: '⏱️',
    path: '/games/timed-button',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'mirror-othello',
    title: 'Mirror Othello',
    description: 'An Othello variant where the board mirrors every 4 turns.',
    thumbnail: '🪞',
    path: '/games/mirror-othello',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'memory-maze',
    title: 'Memory Maze',
    description: 'Memorize the maze in 3 seconds, then navigate in the dark to reach the goal.',
    thumbnail: '🧩',
    path: '/games/memory-maze',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'daily-move-puzzle',
    title: 'Daily One-Move Puzzle',
    description: 'A new one-move winning puzzle every day. Solve and share your attempts.',
    thumbnail: '📅',
    path: '/games/daily-move-puzzle',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'bigger-number',
    title: 'Bigger Number',
    description: 'Pick a tile, reveal at the same time as your opponent — higher number wins. Vs AI or 2-player online.',
    thumbnail: '🀄',
    path: '/games/bigger-number',
    difficulty: 'Easy',
    category: 'Card',
  },
  {
    id: 'territory-number',
    title: 'Territory Number',
    description: 'A 3×3 territory game where number cards capture lines. Place 1–9 strategically — most lines wins.',
    thumbnail: '🎯',
    path: '/games/territory-number',
    difficulty: 'Medium',
    category: 'Strategy',
  },
  {
    id: 'memory-battle',
    title: 'Memory Battle',
    description: 'Five cards flash for 3 seconds, then flip. Find the requested number to score before time runs out.',
    thumbnail: '🧠',
    path: '/games/memory-battle',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'iq-test',
    title: 'IQ Test',
    description: 'A short IQ-style quiz with procedurally generated questions: number sequences, odd-one-out, analogies, and more.',
    thumbnail: '🧩',
    path: '/games/iq-test',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'roulette',
    title: 'Roulette + Martingale Sim',
    description: 'European roulette you can actually play, plus a Monte Carlo simulator that shows how the Martingale strategy goes bust.',
    thumbnail: '🎡',
    path: '/games/roulette',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'monty-hall',
    title: 'Monty Hall',
    description: 'The classic three-door problem. Play it, then run a Monte Carlo simulation that shows Switch beats Stay 2:1.',
    thumbnail: '🚪',
    path: '/games/monty-hall',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'birthday-paradox',
    title: 'Birthday Paradox',
    description: 'How few people do you need before two share a birthday? Play it, then simulate the famous 50% / 99% thresholds.',
    thumbnail: '🎂',
    path: '/games/birthday-paradox',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'coupon-collector',
    title: 'Coupon Collector',
    description: 'How many draws to collect all n items? The classic gacha problem: expected draws ≈ n·ln(n) — the last few items take forever.',
    thumbnail: '🎟️',
    path: '/games/coupon-collector',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'gamblers-ruin',
    title: "Gambler's Ruin",
    description: 'Even with a fair 50/50 game, finite bankroll means ruin probability is (N − a) / N. Make it 49/51 and ruin becomes nearly certain.',
    thumbnail: '💸',
    path: '/games/gamblers-ruin',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'blackjack',
    title: 'Blackjack — Basic Strategy',
    description: 'Play simplified Blackjack with a hint that shows what Basic Strategy says. Then simulate it vs Mimic-Dealer vs Always-Stand and see the edge gap.',
    thumbnail: '🃏',
    path: '/games/blackjack',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'secretary-problem',
    title: 'Secretary Problem',
    description: 'Interview candidates one by one, decide on the spot, no second chances. Try beating the famous 37% rule — then simulate it.',
    thumbnail: '👔',
    path: '/games/secretary-problem',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
];
