/**
 * Shared games data
 */

export interface Game {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  path: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: string;
}

export function getGameCoverPath(gameId: string): string {
  return `/img/games/covers/${gameId}.webp`;
}

export const games: Game[] = [
  {
    id: 'jump-game',
    title: 'Jump Game',
    description: 'Time your jumps, clear each obstacle, and keep the run alive for a new high score.',
    thumbnail: '⬆️',
    path: '/games/jump-game',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Play classic tic-tac-toe against an AI with three difficulty levels.',
    thumbnail: '❌',
    path: '/games/tic-tac-toe',
    difficulty: 'Medium',
    category: 'Strategy',
  },
  {
    id: 'gomoku',
    title: 'Gomoku',
    description: 'Place five stones in a row while the AI searches for threats and blocks.',
    thumbnail: '⚫',
    path: '/games/gomoku',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    description: 'Stack falling blocks, clear lines, and keep the board from filling up.',
    thumbnail: '🟦',
    path: '/games/tetris',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'shogi',
    title: 'Shogi',
    description: 'Play Japanese chess against an AI with drops, promotions, and tactical pressure.',
    thumbnail: '☗',
    path: '/games/shogi',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'othello',
    title: 'Othello',
    description: 'Flip discs, claim corners, and outscore the AI by the final board.',
    thumbnail: '⚪',
    path: '/games/othello',
    difficulty: 'Medium',
    category: 'Strategy',
  },
  {
    id: 'mini-adventure',
    title: 'Mini Adventure',
    description: 'Explore a compact dungeon, manage torchlight, and survive to face the final boss.',
    thumbnail: '🗡️',
    path: '/games/mini-adventure',
    difficulty: 'Hard',
    category: 'RPG',
  },
  {
    id: 'animal-roleplay',
    title: 'Animal Roleplay',
    description: 'Choose a survival role, manage HP and hunger, and score as many turns as you can.',
    thumbnail: '🐾',
    path: '/games/animal-roleplay',
    difficulty: 'Medium',
    category: 'RPG',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Move the paddle, break every brick, and catch power-ups to extend the run.',
    thumbnail: '🧱',
    path: '/games/breakout',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    description: 'Clear enemy waves, take cover behind shields, and hit the bonus UFO.',
    thumbnail: '👾',
    path: '/games/space-invaders',
    difficulty: 'Medium',
    category: 'Arcade',
  },
  {
    id: 'daifugo',
    title: 'Daifugo',
    description: 'Race to empty your hand in Daifugo, solo against AI or online with friends.',
    thumbnail: '🃏',
    path: '/games/daifugo',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'shichinarabe',
    title: 'Shichinarabe',
    description: 'Build from the sevens, manage blocked suits, and empty your hand first.',
    thumbnail: '🃏',
    path: '/games/shichinarabe',
    difficulty: 'Easy',
    category: 'Card',
  },
  {
    id: 'doubt',
    title: 'Doubt',
    description: 'Bluff with face-down cards, challenge suspicious claims, and catch the AI lying.',
    thumbnail: '🃏',
    path: '/games/doubt',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'reverse-jump',
    title: 'Reverse Jump',
    description: 'Jump, duck, and adapt when the controls invert mid-run.',
    thumbnail: '↕️',
    path: '/games/reverse-jump',
    difficulty: 'Medium',
    category: 'Arcade',
  },
  {
    id: 'ghost-tetris',
    title: 'Ghost Tetris',
    description: 'Blocks fade after they lock, so every clear depends on memory.',
    thumbnail: '👻',
    path: '/games/ghost-tetris',
    difficulty: 'Hard',
    category: 'Puzzle',
  },
  {
    id: 'chaos-breakout',
    title: 'Chaos Breakout',
    description: 'Break bricks while gravity, ball speed, and paddle size keep changing.',
    thumbnail: '💥',
    path: '/games/chaos-breakout',
    difficulty: 'Hard',
    category: 'Arcade',
  },
  {
    id: 'doubt-word',
    title: 'Doubt Word',
    description: 'Claim letters and word lengths, then decide when to trust or challenge.',
    thumbnail: '🔤',
    path: '/games/doubt-word',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'timed-button',
    title: 'Timed Button',
    description: 'Stop the sweeping marker inside the target zone — a precision timing challenge.',
    thumbnail: '🎯',
    path: '/games/timed-button',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'mirror-othello',
    title: 'Mirror Othello',
    description: 'Play Othello on a board that mirrors every few turns.',
    thumbnail: '🪞',
    path: '/games/mirror-othello',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'memory-maze',
    title: 'Memory Maze',
    description: 'Study the maze, then navigate with limited vision before time runs out.',
    thumbnail: '🗺️',
    path: '/games/memory-maze',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'daily-move-puzzle',
    title: 'Daily One-Move Puzzle',
    description: 'Solve one daily tactical puzzle and share how many attempts it took.',
    thumbnail: '📅',
    path: '/games/daily-move-puzzle',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'bigger-number',
    title: 'Bigger Number',
    description: 'Reveal numbered tiles at the same time; the higher number wins the round.',
    thumbnail: '🔢',
    path: '/games/bigger-number',
    difficulty: 'Easy',
    category: 'Card',
  },
  {
    id: 'territory-number',
    title: 'Territory Number',
    description: 'Place number cards on a 3x3 board and capture the most scoring lines.',
    thumbnail: '#️⃣',
    path: '/games/territory-number',
    difficulty: 'Medium',
    category: 'Strategy',
  },
  {
    id: 'memory-battle',
    title: 'Memory Battle',
    description: 'Memorize five cards, then pick the requested number under time pressure.',
    thumbnail: '🧠',
    path: '/games/memory-battle',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'iq-test',
    title: 'IQ Test',
    description: 'Answer ten generated pattern and logic questions with instant explanations.',
    thumbnail: '🧩',
    path: '/games/iq-test',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'roulette',
    title: 'Roulette & Martingale',
    description: 'Play European roulette, then simulate how Martingale betting fails under limits.',
    thumbnail: '🎲',
    path: '/games/roulette',
    difficulty: 'Easy',
    category: 'Arcade',
  },
  {
    id: 'monty-hall',
    title: 'Monty Hall',
    description: 'Pick a door, decide whether to switch, and compare the odds with simulation.',
    thumbnail: '🚪',
    path: '/games/monty-hall',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'birthday-paradox',
    title: 'Birthday Paradox',
    description: 'See how quickly shared birthdays appear as the group gets larger.',
    thumbnail: '🎂',
    path: '/games/birthday-paradox',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'coupon-collector',
    title: 'Coupon Collector',
    description: 'Simulate the long tail of collecting every item in a random set.',
    thumbnail: '🎟️',
    path: '/games/coupon-collector',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'gamblers-ruin',
    title: "Gambler's Ruin",
    description: 'Model how bankroll, target, and win rate change the risk of ruin.',
    thumbnail: '💸',
    path: '/games/gamblers-ruin',
    difficulty: 'Easy',
    category: 'Puzzle',
  },
  {
    id: 'blackjack',
    title: 'Blackjack Strategy',
    description: 'Play simplified blackjack with basic-strategy hints and strategy simulations.',
    thumbnail: '🃏',
    path: '/games/blackjack',
    difficulty: 'Medium',
    category: 'Card',
  },
  {
    id: 'texas-holdem',
    title: "Texas Hold'em",
    description: 'Play 100bb no-limit Hold’em against up to seven GTO-inspired CPU opponents.',
    thumbnail: '♠️',
    path: '/games/texas-holdem',
    difficulty: 'Hard',
    category: 'Card',
  },
  {
    id: 'secretary-problem',
    title: 'Secretary Problem',
    description: 'Interview candidates one by one and test the classic 37% stopping rule.',
    thumbnail: '💼',
    path: '/games/secretary-problem',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'bandit',
    title: 'K-armed Bandit',
    description: 'Balance explore vs exploit and compare bandit algorithms over many trials.',
    thumbnail: '🎰',
    path: '/games/bandit',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'bayesian-update',
    title: 'Bayesian Update',
    description: 'Flip a biased coin and watch the posterior estimate update in real time.',
    thumbnail: '📈',
    path: '/games/bayesian-update',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
  {
    id: 'mahjong',
    title: 'Riichi Mahjong',
    description: 'Play a full East-round riichi mahjong game against three AI seats, yaku and fu included.',
    thumbnail: '🀄',
    path: '/games/mahjong',
    difficulty: 'Hard',
    category: 'Strategy',
  },
  {
    id: 'petersburg',
    title: 'St. Petersburg Paradox',
    description: 'Simulate the paradox where infinite expected value still feels overpriced.',
    thumbnail: '🪙',
    path: '/games/petersburg',
    difficulty: 'Medium',
    category: 'Puzzle',
  },
];
