/**
 * External large-scale opening book (public/shogi-opening-book-v3.bin):
 * - binary loader accepts the real committed asset and rejects corrupt buffers
 * - curated book keeps priority for positions it covers (regression safety)
 * - external entries extend coverage once the curated lines end
 * - the independent 32-bit secondary hash rejects 30-bit HashVal collisions
 * - the v3 deviation cover answers natural human moves past ply 12 (v2 stopped at ply 6-8)
 *
 * Uses the REAL committed book (generated by scripts/shogi-import-petashock-book.ts,
 * depth-18-pruned by scripts/shogi-petashock-book-fullcheck.ts, human-deviation cover by
 * scripts/shogi-book-deviation-cover.ts).
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { GenerateMovesImproved } from '@/components/game/ShogiImproved/GenerateMovesImproved';
import { InitialPositionImproved } from '@/components/game/ShogiImproved/InitialPositionImproved';
import { KyokumenImproved } from '@/components/game/ShogiImproved/KyokumenImproved';
import {
  clearExternalOpeningBookForTests,
  getOpeningMoveImproved,
  isExternalOpeningBookLoaded,
  loadExternalOpeningBook,
  openingBookStats,
} from '@/components/game/ShogiImproved/OpeningBookImproved';
import { SENTE, Te } from '@/components/game/ShogiImproved/types';

const bookPath = join(process.cwd(), 'public', 'shogi-opening-book-v3.bin');

function realBookBuffer(): ArrayBuffer {
  const raw = readFileSync(bookPath);
  return raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength) as ArrayBuffer;
}

function startPosition(): KyokumenImproved {
  const k = InitialPositionImproved.createInitialPosition();
  k.setTeban(SENTE);
  return k;
}

function playFromTo(k: KyokumenImproved, fromSuji: number, fromDan: number, toSuji: number, toDan: number): void {
  const from = (fromSuji << 4) + fromDan;
  const to = (toSuji << 4) + toDan;
  const legal = GenerateMovesImproved.generateLegalMoves(k);
  const te = legal.find((m) => m.from === from && m.to === to && !m.promote);
  expect(te, `expected legal move ${fromSuji}${fromDan}->${toSuji}${toDan}`).toBeDefined();
  k.move(te!);
  k.toggleTeban();
}

function isLegal(k: KyokumenImproved, move: Te): boolean {
  return GenerateMovesImproved.generateLegalMoves(k).some((m) => m.equals(move));
}

/** Encode a single-entry external book buffer (format of scripts/shogi-import-petashock-book.ts). */
function encodeBook(entries: Array<{ hashA: number; hashB: number; moves: Array<[number, number, number]> }>): ArrayBuffer {
  let bytes = 8;
  for (const e of entries) bytes += 9 + e.moves.length * 3;
  const buf = Buffer.alloc(bytes);
  buf.writeUInt32LE(0x324b4253, 0); // "SBK2"
  buf.writeUInt32LE(entries.length, 4);
  let o = 8;
  for (const e of entries) {
    buf.writeUInt32LE(e.hashA >>> 0, o); o += 4;
    buf.writeUInt32LE(e.hashB >>> 0, o); o += 4;
    buf.writeUInt8(e.moves.length, o); o += 1;
    for (const [from, to, flags] of e.moves) {
      buf.writeUInt8(from, o); o += 1;
      buf.writeUInt8(to, o); o += 1;
      buf.writeUInt8(flags, o); o += 1;
    }
  }
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

beforeEach(() => {
  clearExternalOpeningBookForTests();
});

afterEach(() => {
  clearExternalOpeningBookForTests();
});

describe('loadExternalOpeningBook', () => {
  it('loads the real committed book asset (>= 150k positions, <= 4MB raw / <= 2.5MB gzipped)', () => {
    const buf = realBookBuffer();
    expect(buf.byteLength).toBeLessThanOrEqual(4_000_000); // static-asset budget guard (raw)
    // The transfer budget is on the gzipped size (the asset is served compressed).
    expect(gzipSync(Buffer.from(buf)).byteLength).toBeLessThanOrEqual(2_500_000);
    const n = loadExternalOpeningBook(buf);
    expect(n).toBeGreaterThanOrEqual(150_000);
    expect(isExternalOpeningBookLoaded()).toBe(true);
  });

  it('rejects a buffer with a wrong magic', () => {
    const buf = realBookBuffer();
    new DataView(buf).setUint32(0, 0xdeadbeef, true);
    expect(loadExternalOpeningBook(buf)).toBe(0);
    expect(isExternalOpeningBookLoaded()).toBe(false);
  });

  it('fails closed on the legacy SBK1 format', () => {
    const legacy = Buffer.alloc(8);
    legacy.writeUInt32LE(0x314b4253, 0);
    legacy.writeUInt32LE(0, 4);
    expect(loadExternalOpeningBook(legacy.buffer.slice(legacy.byteOffset, legacy.byteOffset + legacy.byteLength))).toBe(0);
    expect(isExternalOpeningBookLoaded()).toBe(false);
  });

  it('rejects a truncated buffer', () => {
    const buf = realBookBuffer();
    expect(loadExternalOpeningBook(buf.slice(0, buf.byteLength - 5))).toBe(0);
    expect(isExternalOpeningBookLoaded()).toBe(false);
  });

  it('rejects duplicate primary + secondary entries transactionally', () => {
    const k = startPosition();
    const hashA = k.HashVal >>> 0;
    const hashB = k.SecondaryHashVal >>> 0;
    const move76: [number, number, number] = [(7 << 4) + 7, (7 << 4) + 6, 0];
    const duplicate = encodeBook([
      { hashA, hashB, moves: [move76] },
      { hashA, hashB, moves: [move76] },
    ]);
    expect(loadExternalOpeningBook(duplicate)).toBe(0);
    expect(isExternalOpeningBookLoaded()).toBe(false);
  });

  it('rejects tiny/garbage buffers without touching an already-loaded book', () => {
    expect(loadExternalOpeningBook(new ArrayBuffer(3))).toBe(0);
    expect(loadExternalOpeningBook(realBookBuffer())).toBeGreaterThan(0);
    // A later bad load must keep the good book installed.
    expect(loadExternalOpeningBook(new ArrayBuffer(16))).toBe(0);
    expect(isExternalOpeningBookLoaded()).toBe(true);
  });
});

describe('curated-book priority', () => {
  it('returns the same initial-position move with and without the external book', () => {
    const before = getOpeningMoveImproved(startPosition(), 'master');
    expect(before).not.toBeNull();

    expect(loadExternalOpeningBook(realBookBuffer())).toBeGreaterThan(0);
    const after = getOpeningMoveImproved(startPosition(), 'master');
    expect(after).not.toBeNull();
    expect(after!.equals(before)).toBe(true);
  });

  it('still never returns the weak △8四飛 in the 角道相掛かり ▲6六歩 position (#338 regression)', () => {
    // Same position as the curated regression test in shogiImproved.test.ts, but WITH the
    // external book loaded — curated candidates must keep winning at position level.
    expect(loadExternalOpeningBook(realBookBuffer())).toBeGreaterThan(0);
    const k = startPosition();
    playFromTo(k, 7, 7, 7, 6); // ▲７六歩
    playFromTo(k, 8, 3, 8, 4); // △８四歩
    playFromTo(k, 2, 7, 2, 6); // ▲２六歩
    playFromTo(k, 8, 4, 8, 5); // △８五歩
    playFromTo(k, 8, 8, 7, 7); // ▲７七角
    playFromTo(k, 3, 3, 3, 4); // △３四歩
    playFromTo(k, 6, 7, 6, 6); // ▲６六歩
    const move = getOpeningMoveImproved(k, 'medium');
    expect(move).not.toBeNull();
    const uki84 = (8 << 4) + 4;
    expect(move!.from === (8 << 4) + 2 && move!.to === uki84).toBe(false);
  });
});

describe('external coverage', () => {
  it('extends the book walk well past the curated lines (master, deterministic)', () => {
    expect(loadExternalOpeningBook(realBookBuffer())).toBeGreaterThan(0);
    const externalHitsBefore = openingBookStats.externalHits;

    const k = startPosition();
    let plies = 0;
    for (; plies < 40; plies++) {
      const move = getOpeningMoveImproved(k, 'master');
      if (!move) break;
      expect(isLegal(k, move)).toBe(true);
      k.move(move);
      k.toggleTeban();
    }

    // The curated mainlines are <= ~18 plies and the external book reaches ply 30 on
    // mainlines; the deterministic master walk must stay in book for a while and must
    // consult the external book at least once after the curated line ends. (The walk ends
    // where its specific deterministic path hits a petashock coverage leaf, not at the
    // book's maximum depth.)
    expect(plies).toBeGreaterThanOrEqual(10);
    expect(openingBookStats.externalHits).toBeGreaterThan(externalHitsBefore);
  });

  it('answers a natural non-book human move from the deviation cover (▲4八銀 early)', () => {
    // ▲7六歩 △3四歩 ▲4八銀: a perfectly natural human developing move that is NOT in the
    // petashock lines (engine-vs-engine books never play it here). v1 dropped out of book;
    // the v2 deviation cover stores the engine's depth-18 reply for exactly this kind of
    // position, so the side to move (the AI as gote) must still get a book move.
    const k = startPosition();
    playFromTo(k, 7, 7, 7, 6); // ▲７六歩
    playFromTo(k, 3, 3, 3, 4); // △３四歩
    playFromTo(k, 3, 9, 4, 8); // ▲４八銀 (deviation)
    expect(getOpeningMoveImproved(k, 'master')).toBeNull(); // precondition: not yet loaded

    expect(loadExternalOpeningBook(realBookBuffer())).toBeGreaterThan(0);
    const reply = getOpeningMoveImproved(k, 'master');
    expect(reply).not.toBeNull();
    expect(isLegal(k, reply!)).toBe(true);
  });

  it('answers the classic human moves ▲5六歩 / ▲6八玉 after ▲7六歩 △8四歩 (v3 deviation cover)', () => {
    // Two of the most common club-player moves (中飛車 / 矢倉 move orders) — both OUTSIDE the
    // engine-vs-engine petashock lines AND outside v2's MultiPV-12 window at this seed. The v3
    // cover (MultiPV 30 at shallow plies, AI-aware seed walk) stores a depth-18 reply for each,
    // so the AI as gote answers from book instead of dropping out at ply 3.
    expect(loadExternalOpeningBook(realBookBuffer())).toBeGreaterThan(0);
    for (const [fromSuji, fromDan, toSuji, toDan] of [
      [5, 7, 5, 6], // ▲５六歩 (中飛車)
      [5, 9, 6, 8], // ▲６八玉 (矢倉/左美濃 order)
    ]) {
      const k = startPosition();
      playFromTo(k, 7, 7, 7, 6); // ▲７六歩
      playFromTo(k, 8, 3, 8, 4); // △８四歩
      playFromTo(k, fromSuji, fromDan, toSuji, toDan);
      const reply = getOpeningMoveImproved(k, 'master');
      expect(reply, `expected a book reply to ${fromSuji}${fromDan}->${toSuji}${toDan}`).not.toBeNull();
      expect(isLegal(k, reply!)).toBe(true);
    }
  });

  it('serves a synthetic entry only for the exact primary + secondary pair', () => {
    // Position after ▲３八銀 — no curated line starts with it, so only the external map
    // can answer. Craft a synthetic book that recommends △８四歩 there.
    const k = startPosition();
    playFromTo(k, 3, 9, 3, 8); // ▲３八銀
    expect(getOpeningMoveImproved(k, 'master')).toBeNull(); // precondition: curated-free

    const hashA = k.HashVal >>> 0;
    const hashB = k.SecondaryHashVal >>> 0;
    const move84: [number, number, number] = [(8 << 4) + 3, (8 << 4) + 4, 0]; // △８四歩

    // Same primary with a wrong independent lock: must be treated as out-of-book.
    expect(loadExternalOpeningBook(encodeBook([{ hashA, hashB: hashB ^ 0xffffffff, moves: [move84] }]))).toBe(1);
    expect(getOpeningMoveImproved(k, 'master')).toBeNull();

    // Exact pair: the synthetic external move is returned.
    expect(loadExternalOpeningBook(encodeBook([{ hashA, hashB, moves: [move84] }]))).toBe(1);
    const move = getOpeningMoveImproved(k, 'master');
    expect(move).not.toBeNull();
    expect(move!.from).toBe((8 << 4) + 3);
    expect(move!.to).toBe((8 << 4) + 4);
  });

  it('drops external moves that are not legal in the position (corrupt/colliding data)', () => {
    const k = startPosition();
    playFromTo(k, 3, 9, 3, 8); // ▲３八銀 (curated-free)
    const hashA = k.HashVal >>> 0;
    const hashB = k.SecondaryHashVal >>> 0;
    // "Move" from the empty square 5e — can never match a legal move.
    expect(loadExternalOpeningBook(encodeBook([{ hashA, hashB, moves: [[(5 << 4) + 5, (5 << 4) + 4, 0]] }]))).toBe(1);
    expect(getOpeningMoveImproved(k, 'master')).toBeNull();
  });
});
