// gen-tables.mjs
//
// Extracts the move tables (canMove / canJump / diff) from the existing TS engine
// (src/components/game/ShogiImproved/GenerateMovesImproved.ts) plus komaValue /
// canPromote from types.ts, and emits an AssemblyScript module
// (wasm-spike/assembly/tables.ts) so the WASM port is guaranteed to use the exact
// same movement semantics as the JS engine.
//
// Usage: node wasm-spike/gen-tables.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const gmSrc = readFileSync(
  new URL('../src/components/game/ShogiImproved/GenerateMovesImproved.ts', import.meta.url),
  'utf8'
);
const tySrc = readFileSync(
  new URL('../src/components/game/ShogiImproved/types.ts', import.meta.url),
  'utf8'
);

/** Extract `const <name>[: type] = [...];` and eval the array literal. */
function grab(src, name) {
  // Single-line arrays first (e.g. diffDan), then multi-line arrays whose
  // opening bracket is followed by a newline and which close at column 0.
  const single = new RegExp(`const ${name}[^=]*=\\s*(\\[[^\\]\\n]*\\]);`);
  const multi = new RegExp(`const ${name}[^=]*=\\s*(\\[\\s*\\n[\\s\\S]*?\\n\\]);`);
  const m = src.match(single) || src.match(multi);
  if (!m) throw new Error(`Could not extract ${name}`);
  // eslint-disable-next-line no-new-func
  return Function(`return (${m[1]})`)();
}

const diffDan = grab(gmSrc, 'diffDan');
const diffSuji = grab(gmSrc, 'diffSuji');
const canMove = grab(gmSrc, 'canMove'); // 12 x 48 booleans
const canJump = grab(gmSrc, 'canJump'); // 8 x 48 booleans
const komaValue = grab(tySrc, 'komaValue'); // 48 numbers
const canPromote = grab(tySrc, 'canPromote'); // 48 booleans

if (canMove.length !== 12 || canJump.length !== 8) {
  throw new Error('Unexpected table shape');
}

const diff = diffSuji.map((s, i) => s * 16 + diffDan[i]);

/** Flatten a table of boolean rows into rows padded to 64 entries of 0/1. */
function flatten01(rows, rowLen = 64) {
  const out = [];
  for (const row of rows) {
    for (let i = 0; i < rowLen; i++) out.push(row[i] ? 1 : 0);
  }
  return out;
}

function pad(arr, len, fill = 0) {
  const out = arr.slice();
  while (out.length < len) out.push(fill);
  return out;
}

function fmt(arr, perLine = 32) {
  const lines = [];
  for (let i = 0; i < arr.length; i += perLine) {
    lines.push('  ' + arr.slice(i, i + perLine).join(','));
  }
  return lines.join(',\n');
}

const output = `// AUTO-GENERATED by wasm-spike/gen-tables.mjs — do not edit by hand.
// Source of truth: src/components/game/ShogiImproved/GenerateMovesImproved.ts / types.ts

// 12 move directions, encoded as (suji*16 + dan) offsets.
export const DIFF: StaticArray<i32> = StaticArray.fromArray<i32>([
${fmt(diff, 12)}
]);

// canMove[direct*64 + koma] (12 directions x 64 piece codes, padded from 48).
export const CAN_MOVE: StaticArray<u8> = StaticArray.fromArray<u8>([
${fmt(flatten01(canMove))}
]);

// canJump[direct*64 + koma] (8 directions x 64 piece codes, padded from 48).
export const CAN_JUMP: StaticArray<u8> = StaticArray.fromArray<u8>([
${fmt(flatten01(canJump))}
]);

// canPromote[koma] (padded from 48 to 64).
export const CAN_PROMOTE: StaticArray<u8> = StaticArray.fromArray<u8>([
${fmt(pad(canPromote.map((b) => (b ? 1 : 0)), 64))}
]);

// komaValue[koma] (padded from 48 to 64).
export const KOMA_VALUE: StaticArray<i32> = StaticArray.fromArray<i32>([
${fmt(pad(komaValue, 64), 16)}
]);
`;

writeFileSync(new URL('./assembly/tables.ts', import.meta.url), output);
console.log('Wrote wasm-spike/assembly/tables.ts');
console.log('diff =', JSON.stringify(diff));
