/**
 * positionHistory.ts — the already-played positions of the current game, in
 * the form the WASM search wants them.
 *
 * Why this exists: the search kept its own repetition stack, but that stack
 * only ever contained positions the search itself had walked into, and it was
 * reset at the start of every `searchBestMove`. Nothing ever told the engine
 * what had actually happened on the board, so it could neither see a 千日手
 * coming nor notice that a line simply returned the game to a position it had
 * already been in. Shuffling looked free.
 *
 * The transport is a flat `[primary, secondary, primary, secondary, …]` list
 * of Zobrist hash pairs in game order, because that survives structured clone
 * to the worker unchanged and costs one number pair per ply. The JS and WASM
 * Zobrist tables are generated by the same deterministic PRNG in the same
 * order, so `KyokumenImproved.HashVal` / `SecondaryHashVal` are exactly what
 * the engine computes for itself (locked down by a unit test).
 *
 * The list covers plies 0 .. n-1 and deliberately STOPS before the position
 * being searched: the search contributes the root's own occurrence when it
 * pushes ply 0, so including it here would double count.
 *
 * Cost: the replay generates the legal moves at every ply, which is ~10ms for
 * a 200-ply game and ~6ms for a typical one. It runs once per AI request, on
 * the main thread, immediately before handing the position to a worker that
 * will think for one to five seconds - so a cache is not worth the extra state
 * it would have to keep correct across 待った and kifu import.
 */

import { GenerateMovesImproved } from './GenerateMovesImproved';
import { KyokumenImproved } from './KyokumenImproved';
import { Te } from './types';

/** The subset of a recorded kifu move needed to replay it. */
export interface ReplayableMove {
  koma: number;
  from: number;
  to: number;
  promote: boolean;
}

/**
 * Replay `moves` from `start` and collect the hash pair of every position
 * that was on the board before each move.
 *
 * `expected` is the position the caller is about to search. The replay must
 * land exactly on it; if it does not — an imported kifu that began mid-game, a
 * restored save without its move list, any future divergence — this returns an
 * empty history rather than a wrong one. An empty history is always safe: the
 * engine then behaves exactly as it did before this feature existed.
 */
export function buildPositionHistoryHashes(
  start: KyokumenImproved,
  moves: readonly ReplayableMove[],
  expected: KyokumenImproved
): number[] {
  const hashes: number[] = [];
  const k = start.clone();

  for (const m of moves) {
    hashes.push(k.HashVal, k.SecondaryHashVal);
    const legal = GenerateMovesImproved.generateLegalMoves(k);
    const te = legal.find(
      (c: Te) =>
        c.koma === m.koma && c.from === m.from && c.to === m.to && c.promote === m.promote
    );
    if (!te) return [];
    te.capture = k.get(te.to);
    k.move(te);
    k.toggleTeban();
  }

  if (k.HashVal !== expected.HashVal || k.SecondaryHashVal !== expected.SecondaryHashVal) {
    return [];
  }
  return hashes;
}
